const personas = [
  {
    id: 1,
    nombre: "Patric",
    apellido: "Stonnell",
    email: "pstonnell0@narod.ru",
    genero: "Male",
    edad: 64,
  },
  {
    id: 2,
    nombre: "Elroy",
    apellido: "Duguid",
    email: "eduguid1@geocities.com",
    genero: "Male",
    edad: 64,
  },
  {
    id: 3,
    nombre: "Kingsly",
    apellido: "Bontoft",
    email: "kbontoft2@shareasale.com",
    genero: "Male",
    edad: 33,
  },
  {
    id: 4,
    nombre: "Will",
    apellido: "Scrivin",
    email: "wscrivin3@patch.com",
    genero: "Male",
    edad: 39,
  },
  {
    id: 5,
    nombre: "Lizette",
    apellido: "Dignum",
    email: "ldignum4@pbs.org",
    genero: "Female",
    edad: 60,
  },
  {
    id: 6,
    nombre: "Inga",
    apellido: "Clother",
    email: "iclother5@linkedin.com",
    genero: "Female",
    edad: 23,
  },
  {
    id: 7,
    nombre: "Gustavo",
    apellido: "Kilfeather",
    email: "gkilfeather6@printfriendly.com",
    genero: "Male",
    edad: 50,
  },
  {
    id: 8,
    nombre: "Miltie",
    apellido: "Batsford",
    email: "mbatsford7@wisc.edu",
    genero: "Male",
    edad: 52,
  },
  {
    id: 9,
    nombre: "Kennie",
    apellido: "Mecco",
    email: "kmecco8@chronoengine.com",
    genero: "Male",
    edad: 43,
  },
  {
    id: 10,
    nombre: "Madison",
    apellido: "Ashwell",
    email: "mashwell9@wikispaces.com",
    genero: "Male",
    edad: 55,
  },
  {
    id: 11,
    nombre: "Dagny",
    apellido: "Redparth",
    email: "dredpartha@japanpost.jp",
    genero: "Male",
    edad: 54,
  },
  {
    id: 12,
    nombre: "Codie",
    apellido: "Illwell",
    email: "cillwellb@va.gov",
    genero: "Female",
    edad: 20,
  },
  {
    id: 13,
    nombre: "Sholom",
    apellido: "De Souza",
    email: "sdesouzac@vinaora.com",
    genero: "Male",
    edad: 37,
  },
  {
    id: 14,
    nombre: "Harriette",
    apellido: "Rowantree",
    email: "hrowantreed@washingtonpost.com",
    genero: "Female",
    edad: 54,
  },
  {
    id: 15,
    nombre: "Leroi",
    apellido: "Pocknoll",
    email: "lpocknolle@i2i.jp",
    genero: "Male",
    edad: 58,
  },
  {
    id: 16,
    nombre: "Phillipp",
    apellido: "Zecchini",
    email: "pzecchinif@illinois.edu",
    genero: "Male",
    edad: 47,
  },
  {
    id: 17,
    nombre: "Hester",
    apellido: "Heims",
    email: "hheimsg@ted.com",
    genero: "Female",
    edad: 38,
  },
  {
    id: 18,
    nombre: "Nicolis",
    apellido: "Ingry",
    email: "ningryh@google.de",
    genero: "Male",
    edad: 30,
  },
  {
    id: 19,
    nombre: "Claudette",
    apellido: "Ruggier",
    email: "cruggieri@yellowbook.com",
    genero: "Female",
    edad: 35,
  },
  {
    id: 20,
    nombre: "Guillema",
    apellido: "Mifflin",
    email: "gmifflinj@census.gov",
    genero: "Female",
    edad: 44,
  },
  {
    id: 21,
    nombre: "Ania",
    apellido: "Crepin",
    email: "acrepink@adobe.com",
    genero: "Female",
    edad: 41,
  },
  {
    id: 22,
    nombre: "Clotilda",
    apellido: "Yesichev",
    email: "cyesichevl@bloglovin.com",
    genero: "Female",
    edad: 52,
  },
  {
    id: 23,
    nombre: "Willdon",
    apellido: "Antcliff",
    email: "wantcliffm@example.com",
    genero: "Male",
    edad: 42,
  },
  {
    id: 24,
    nombre: "Mallory",
    apellido: "Yeo",
    email: "myeon@mayoclinic.com",
    genero: "Male",
    edad: 63,
  },
  {
    id: 25,
    nombre: "Zacharia",
    apellido: "Beckitt",
    email: "zbeckitto@yandex.ru",
    genero: "Male",
    edad: 57,
  },
  {
    id: 26,
    nombre: "Meta",
    apellido: "Ryde",
    email: "mrydep@opensource.org",
    genero: "Female",
    edad: 22,
  },
  {
    id: 27,
    nombre: "Poul",
    apellido: "Heinzler",
    email: "pheinzlerq@unblog.fr",
    genero: "Male",
    edad: 57,
  },
  {
    id: 28,
    nombre: "Padraig",
    apellido: "Eastgate",
    email: "peastgater@51.la",
    genero: "Male",
    edad: 48,
  },
  {
    id: 29,
    nombre: "Vivie",
    apellido: "Woodard",
    email: "vwoodards@rambler.ru",
    genero: "Female",
    edad: 34,
  },
  {
    id: 30,
    nombre: "Margette",
    apellido: "Issacoff",
    email: "missacofft@ucoz.com",
    genero: "Female",
    edad: 61,
  },
  {
    id: 31,
    nombre: "Almeria",
    apellido: "Bullock",
    email: "abullocku@xing.com",
    genero: "Female",
    edad: 35,
  },
  {
    id: 32,
    nombre: "Vachel",
    apellido: "Baldrick",
    email: "vbaldrickv@godaddy.com",
    genero: "Male",
    edad: 18,
  },
  {
    id: 33,
    nombre: "Heinrik",
    apellido: "Fernandes",
    email: "hfernandesw@admin.ch",
    genero: "Male",
    edad: 36,
  },
  {
    id: 34,
    nombre: "Agneta",
    apellido: "Auden",
    email: "aaudenx@soundcloud.com",
    genero: "Female",
    edad: 42,
  },
  {
    id: 35,
    nombre: "Matteo",
    apellido: "Huddart",
    email: "mhuddarty@ihg.com",
    genero: "Male",
    edad: 40,
  },
  {
    id: 36,
    nombre: "Celesta",
    apellido: "Moyse",
    email: "cmoysez@mediafire.com",
    genero: "Female",
    edad: 51,
  },
  {
    id: 37,
    nombre: "Brandais",
    apellido: "Caesman",
    email: "bcaesman10@e-recht24.de",
    genero: "Female",
    edad: 45,
  },
  {
    id: 38,
    nombre: "Kerwin",
    apellido: "Garza",
    email: "kgarza11@livejournal.com",
    genero: "Male",
    edad: 30,
  },
  {
    id: 39,
    nombre: "Deborah",
    apellido: "Dashkov",
    email: "ddashkov12@zimbio.com",
    genero: "Female",
    edad: 48,
  },
  {
    id: 40,
    nombre: "Flo",
    apellido: "Devinn",
    email: "fdevinn13@cdbaby.com",
    genero: "Female",
    edad: 56,
  },
  {
    id: 41,
    nombre: "Halsey",
    apellido: "Clevely",
    email: "hclevely14@miitbeian.gov.cn",
    genero: "Male",
    edad: 36,
  },
  {
    id: 42,
    nombre: "Francesco",
    apellido: "Sutherns",
    email: "fsutherns15@google.co.jp",
    genero: "Male",
    edad: 25,
  },
  {
    id: 43,
    nombre: "Moira",
    apellido: "Simioni",
    email: "msimioni16@xinhuanet.com",
    genero: "Female",
    edad: 38,
  },
  {
    id: 44,
    nombre: "Cross",
    apellido: "Beedie",
    email: "cbeedie17@yolasite.com",
    genero: "Male",
    edad: 31,
  },
  {
    id: 45,
    nombre: "Vina",
    apellido: "Carrack",
    email: "vcarrack18@loc.gov",
    genero: "Female",
    edad: 25,
  },
  {
    id: 46,
    nombre: "Alfy",
    apellido: "Breton",
    email: "abreton19@sogou.com",
    genero: "Male",
    edad: 62,
  },
  {
    id: 47,
    nombre: "Daron",
    apellido: "Jirka",
    email: "djirka1a@irs.gov",
    genero: "Male",
    edad: 53,
  },
  {
    id: 48,
    nombre: "Reuven",
    apellido: "Munning",
    email: "rmunning1b@eepurl.com",
    genero: "Male",
    edad: 60,
  },
  {
    id: 49,
    nombre: "Danice",
    apellido: "Teacy",
    email: "dteacy1c@cbsnews.com",
    genero: "Female",
    edad: 39,
  },
  {
    id: 50,
    nombre: "Dulcinea",
    apellido: "Scullion",
    email: "dscullion1d@addthis.com",
    genero: "Female",
    edad: 33,
  },
];
